# Generated by Django 4.1.7 on 2023-03-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_comment_comment_blog_commen_created_0e6ed4_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="saved_posts",
            field=models.ManyToManyField(related_name="users_saved", to="blog.post"),
        ),
    ]
