# Generated by Django 4.1.7 on 2023-04-02 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field="__all__"
        ),
    ]
