# Generated by Django 4.1.7 on 2023-04-03 01:04

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
