# Generated by Django 4.1.7 on 2023-04-02 15:43

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
